# Site settings
title: Poised-flw的前端博客
email: luofeihit2010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    低调的前端工程师，涉猎PHP、NODE等后端技术，对服务器也有相当的兴趣，承接各种私活~
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.vim.ren" # the base hostname & protocol for your site

port: 8888
host: 127.0.0.1
detach: true

#twitter_username: jekyllrb
github_username: luofei2011 

# Build settings
markdown: kramdown 
#highlighter: pygments
kramdown:
    input: GFM
    syntax_highlighter: rouge

gems: 
    - jekyll-paginate

# pagination
paginate: 10
paginate_path: "page:num"
